In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:15pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:15pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<font size="6" color="red">ch09. 파일 입/출력 프로그래밍</font>
- 파일 : txt, pickle(머신러닝모델저장, 넘파이배열저장), csv, json, h5(딥러닝 모델저장)

# 1절. txt.파일에 데이터 저장하고 불러오기
## 1.1 write
- write(), writelines()

In [2]:
f = open('data/ch09.txt', 'w') # encoding= 'cp949'(win) / 'utf-8'(mac, linux)
# w 또는 wt : 기존의 파일이 있는 경우 덮어쓰기, 파일이 없는 경우 생성하여 쓰기
# a 또는 at : 기존의 파일이 있는경우 append, 파일이 없는 경우 생성하고 쓰기
# r 또는 rt : mode의 기본값. 파일이 있는 경우 파일을 열고, 파일이 없는 경우 예외 발생
print("쓰기 가능한지 :", f.writable())

쓰기 가능한지 : True

In [4]:
f.write('Hello\nWorld\n')
f.close()

In [6]:
# with 구문을 사용하면 매번 close하는 코드가 불필요
with open('data/ch09.txt', 'a') as f: # encoding='cp949'
    f.write('Python is easy.\nPython is smart.\n')

In [8]:
with open('data/ch09.txt', 'a') as f: # encoding='cp949'
    print('print함수는 파일출력, 화면출력\n', file=f)
# 주피터노트북에서는 utf-8 인코딩 방식으로 한글text가 열려.

- utf-8 / UTF-8 / UTF8 : 한글조합형 - 주피터노트북에서
- euc-kf : 한글완성형 (믜x)
- cp949 : 확장된 한글완성형(믜o) - open()함수 기본 encoding방식, 엑셀에서

In [9]:
with open('data/ch09.txt', 'w', encoding='utf-8')as f:
    # 방법 1
    f.write('홍길동,30,서울\n')
    f.write('김길동,25,안양\n')
    # 방법 2
    text_list = ['홍길동,30,서울\n', '김길동,25,안양\n']
    for line in text_list:
        f.write(line)
    # 방법 3
    f.writelines(text_list)

## 1.2 read
- read(), readline(), readlines()

In [10]:
# 방법 1 : 파일을 한번에 읽어오기
with open('data/ch09.txt', 'r', encoding='utf-8')as txtfile:
    filecontent = txtfile.read()
filecontent

'홍길동,30,서울\n김길동,25,안양\n홍길동,30,서울\n김길동,25,안양\n홍길동,30,서울\n김길동,25,안양\n'

In [11]:
# 방법 2 :파일을 한줄씩 읽고 출력
with open('data/ch09.txt', 'rt', encoding='utf-8')as txtfile:
    line = txtfile.readline() # 한줄 읽기
    while line!= '' :
        print(line, end='') # line에 \n이 포함되어 있음
        line = txtfile.readline()

홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양

In [14]:
# 방법 3 : 파일을 한꺼번에 여러줄 읽어 list로 받기
with open('data/ch09.txt', 'r', encoding='UTF-8') as txtfile:
    lines = txtfile.readlines()
print(lines)

['홍길동,30,서울\n', '김길동,25,안양\n', '홍길동,30,서울\n', '김길동,25,안양\n', '홍길동,30,서울\n', '김길동,25,안양\n']

In [16]:
for line in lines:
    print(line, end='')

홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양
홍길동,30,서울
김길동,25,안양

# 2절. 피클을 이용한 객체 저장 및 불러오기
## 2.1 형식이 있는 텍스트 데이터 불러오기
- ch09_member.txt => 객체 list

In [54]:
with open('data/ch09_member.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()
for line in lines:
    #print(line)
    data = line.strip().split(', ')
    name = data[0]
    age = int(data[1].strip())
    email = data[2].strip()
    address = data[3].strip()
    print(f"이름은:{name}, 나이는:{age}, 메일{email}, 주소:{address}")

이름은:홍길동, 나이는:20, 메일kildong@hong.com, 주소:서울시 관악구
이름은:홍길숙, 나이는:25, 메일kilsuk1@hong.com, 주소:서울시 영등포구
이름은:신길동, 나이는:30, 메일shinkil@hong.com, 주소:서울시 동작구

In [92]:
class Member:
    def __init__(self, name, age, email, address):
        self.name = name
        self.age = age
        self.email = email
        self.address = address
    def __str__(self):
        return "{},{},{},{}".format(self.name, 
                                    self.age, 
                                    self.email, 
                                    self.address)
    def __eq__(self, other):
        if isinstance(other, Member):
            return self.__str__() == other.__str__()
        return False
    
    def as_dict(self): # 객체를 딕셔너리로 return
        return {'name':self.name, 'age':self.age, 'email':self.email, 'address':self.address}
    def as_list(self): # 객체를 list로 return
        return [self.name, self.age, self.email, self.address]

In [91]:
member = Member("홍길동", 33, 'hong@h.co.kr', '신림동')
member2 = Member("홍길동", 33, 'hong@h.co.kr', '신림동')
print(id(member), id(member2))
print(member == member2)
print(member.__eq__(member2))
print(member)
print(member.as_dict())
print(member.__dict__)
print(member.as_list())

2042976201472 2042976191152
True
True
홍길동,33,hong@h.co.kr,신림동
{'name': '홍길동', 'age': 33, 'email': 'hong@h.co.kr', 'address': '신림동'}
{'name': '홍길동', 'age': 33, 'email': 'hong@h.co.kr', 'address': '신림동'}
['홍길동', 33, 'hong@h.co.kr', '신림동']

In [93]:
# 파일의 내용을 member list나 딕셔너리 list로 만들기
member_list = [] # 파일의 내용이 member객체로 append
member_dict_list = []
with open('data/ch09_member.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()
for line in lines:
    data = line.strip().split(', ')
    name = data[0]
    age = int(data[1])
    email = data[2]
    address = data[3]
    member = Member(name, age, email, address)
    #print(member)
    member_list.append(member)
    member_dict_list.append(member.__dict__)

In [73]:
[member.__str__() for member in member_list]

['홍길동,20,kildong@hong.com,서울시 관악구',
 '홍길숙,25,kilsuk1@hong.com,서울시 영등포구',
 '신길동,30,shinkil@hong.com,서울시 동작구']

In [74]:
member_dict_list

[{'name': '홍길동', 'age': 20, 'email': 'kildong@hong.com', 'address': '서울시 관악구'},
 {'name': '홍길숙',
  'age': 25,
  'email': 'kilsuk1@hong.com',
  'address': '서울시 영등포구'},
 {'name': '신길동', 'age': 30, 'email': 'shinkil@hong.com', 'address': '서울시 동작구'}]

## 2.2 피클링
- member_list -> 피클파일에 쓰기
- 피클파일을 읽기 -> loaded_member_list

In [77]:
for member in member_list:
    print(member)

홍길동,20,kildong@hong.com,서울시 관악구
홍길숙,25,kilsuk1@hong.com,서울시 영등포구
신길동,30,shinkil@hong.com,서울시 동작구

In [94]:
# 피클링(확장자 : pkl, pickle, data)을 이용한 객체를 파일에 저장하기
import pickle
with open('data/ch09_member.pkl', 'wb') as f:
    pickle.dump(member_list, f)

In [95]:
# 피클링을 이용한 파일에서 객체 데이터 읽기
with open('data/ch09_member.pkl', 'rb') as f:
    loaded_member_list = pickle.load(f)

In [96]:
# member_list
# loaded_member_list
for member, loaded_member in zip(member_list, loaded_member_list):
    print(member, ' / ', loaded_member)

홍길동,20,kildong@hong.com,서울시 관악구  /  홍길동,20,kildong@hong.com,서울시 관악구
홍길숙,25,kilsuk1@hong.com,서울시 영등포구  /  홍길숙,25,kilsuk1@hong.com,서울시 영등포구
신길동,30,shinkil@hong.com,서울시 동작구  /  신길동,30,shinkil@hong.com,서울시 동작구

In [97]:
for member, loaded_member in zip(member_list, loaded_member_list):
    print(member==loaded_member)

True
True
True

# 3절. csv파일 읽기/쓰기
- csv 파일의 자료를 리스트 데이터로 읽고/쓰기 - 3.1과 3.2절
- csv 파일의 자료를 딕셔너리 데이터로 읽고/쓰기 - 3.3과 3.4절
- csv 파일의 자료를 데이터 프레임으로 읽고/쓰기 - 11장
## 3.1 reader

In [6]:
import csv
with open('data/ch09_member1.csv', 'r', encoding="utf-8") as f:
    reader = csv.reader(f)
#     print(list(reader))
    for row in reader:
        print(row)

['홍길동', '20', 'kildong@hong.com', '서울시 관악구']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구']
['신길동', '30', 'sindong@hong.com', '서울시 동작구']

In [9]:
with open('data/ch09_member1-cp.csv',) as f:
    reader = csv.reader(f)
    result = list(reader)
for row in result:
    print(row)

['홍길동', '20', 'kildong@hong.com', '서울시 관악구', '']
['김길동', '40', 'kimdong@hong.com', '서울시 영등포구', '팀장']
['신길동', '30', 'sindong@hong.com', '서울시 동작구', '']

In [12]:
import csv
with open('data/ch09_member1.csv', 'r', encoding="utf-8") as f:
    reader = csv.reader(f, quoting=csv.QUOTE_NONNUMERIC)
    for row in reader:
        print(row)

['홍길동', 20.0, 'kildong@hong.com', '서울시 관악구']
['김길동', 40.0, 'kimdong@hong.com', '서울시 영등포구']
['신길동', 30.0, 'sindong@hong.com', '서울시 동작구']

## 3.2 writer

In [14]:
user_list = [['홍길동', 20, 'kildong@hong.com', '서울시 관악구'],
             ['김길동', 40, 'kimdong@hong.com', '서울시 영등포구'],
             ['신길동', 30, 'sindong@hong.com', '서울시 동작구']]

In [17]:
with open('data/ch09_member2-write-cp.csv', 'w',newline='') as f:
    writer = csv.writer(f)
    for user in user_list:
        writer.writerow(user)

In [18]:
with open('data/ch09_member2-write-cp.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerows(user_list)

## 3.3 DicReader
- csv 파일의 자료를 딕셔너리 데이터로 읽기

In [21]:
with open('data/ch09_member3.csv', 'r', encoding='utf-8') as f:
    dict_reader = csv.DictReader(f, restval='')
    result = list(dict_reader)
result

[{'name': '홍길동',
  'age': '20',
  'email': 'h@h.com',
  'address': '서울시 관악구',
  'job': ''},
 {'name': '신길동',
  'age': '40',
  'email': 's@h.com',
  'address': '서울시 영등포구',
  'job': '팀장'},
 {'name': '김길동',
  'age': '30',
  'email': 'k@h.com',
  'address': '서울시 동작구',
  'job': ''}]

In [22]:
import pandas as pd
pd.read_csv('data/ch09_member3.csv') # 11장

  name  age    email   address  job
0  홍길동   20  h@h.com   서울시 관악구  NaN
1  신길동   40  s@h.com  서울시 영등포구   팀장
2  김길동   30  k@h.com   서울시 동작구  NaN

In [25]:
# header가 없는 csv파일을 딕셔너리로 읽기
with open('data/ch09_member1-cp.csv', 'r')as f:
    dict_reader = csv.DictReader(f, fieldnames=['이름', '나이', '이메일', '주소', '직책'])
    for row in dict_reader:
        print(row)

{'이름': '홍길동', '나이': '20', '이메일': 'kildong@hong.com', '주소': '서울시 관악구', '직책': ''}
{'이름': '김길동', '나이': '40', '이메일': 'kimdong@hong.com', '주소': '서울시 영등포구', '직책': '팀장'}
{'이름': '신길동', '나이': '30', '이메일': 'sindong@hong.com', '주소': '서울시 동작구', '직책': ''}

In [27]:
with open('data/ch09_member1.csv', 'r', encoding='utf-8') as f:
    dict_reader = csv.DictReader(f, fieldnames=['이름', '나이', '이메일', '주소'])
    result = list(dict_reader)
for row in result:
    print(row)

{'이름': '홍길동', '나이': '20', '이메일': 'kildong@hong.com', '주소': '서울시 관악구'}
{'이름': '김길동', '나이': '40', '이메일': 'kimdong@hong.com', '주소': '서울시 영등포구'}
{'이름': '신길동', '나이': '30', '이메일': 'sindong@hong.com', '주소': '서울시 동작구'}

In [28]:
result

[{'이름': '홍길동', '나이': '20', '이메일': 'kildong@hong.com', '주소': '서울시 관악구'},
 {'이름': '김길동', '나이': '40', '이메일': 'kimdong@hong.com', '주소': '서울시 영등포구'},
 {'이름': '신길동', '나이': '30', '이메일': 'sindong@hong.com', '주소': '서울시 동작구'}]

## 3.4 DictWriter
- 딕셔너리 리스트를 csv 파일로 쓰기

In [30]:
fieldnames = list(result[0].keys())
fieldnames

['이름', '나이', '이메일', '주소']

In [31]:
with open('data/ch09_member4.csv', 'w', encoding='UTF-8', newline='')as f:
    dict_writer = csv.DictWriter(f, fieldnames=fieldnames)
    dict_writer.writeheader() # header한줄 쓰기
#     for user in result:
#         dict_writer.writerows(user)
    dict_writer.writerows(result)

# 4절. JSON파일에 저장하고 불러오기(dump, load)
## 4.1 JSON dump(파일에 저장)
1. 딕셔너리 리스트 데이터를 json파일로
2. 객체 리스트 데이터를 json파일로

In [36]:
data = [{'이름': '홍길동', '나이': '20', '이메일': 'kildong@hong.com', '주소': '서울시 관악구'},
        {'이름': '김길동', '나이': '40', '이메일': 'kimdong@hong.com', '주소': '서울시 영등포구'},
        {'이름': '신길동', '나이': '30', '이메일': 'sindong@hong.com', '주소': '서울시 동작구'}]

In [ ]:
# data = [{'name':'hong', 'age':20}]

In [40]:
# 1. 딕셔너리 리스트를 json파일로 저장
# ensure_ascii옵션의 역할 : ASCII코드 범위를 넘어선 문자를 어떻게 처리할지
# True(기본값) : ASCII코드 범위를 넘어선 한글은 유니코드로 저장
# False : 비ASCII 문자의 원래 형태로 저장
import json
with open('data/ch09_member1.json', 'w', encoding='utf-8') as jsonfile:
    json.dump(data, jsonfile, ensure_ascii=False, indent=' ')

In [49]:
# 2. 객체리스트를 json파일로 저장(dump)
class Member:
    def __init__(self, name, age, email, address):
        self.name = name
        self.age = age
        self.email = email
        self.address = address
    def as_dict(self):
        '객체를 딕셔너리로 바꿔 return (json.dump함수 사용에 필요)'
#         return {"name":slef.name, "age":self.age, "email":self.email, "address":self.address}
        return self.__dict__
    def __str__(self):
        return " 이름 {} 나이 {} 메일 {} {} 주거중".format(self.name, self.age, self.email, self.address)
    def __eq__(self, other):
        '''
        m1.__eq__(m2) 호출시 두 객체의 속성변수의 값이 모두 일치하는지 여부
        m1 == m2 구현시 m1.__eq__(m2)호출
        '''
        if isinstance(other, Member):
            return self.__str__() == other.__str__()
        else:
            return False

In [50]:
member1 = Member("홍길동", 20, "h@h.co.kr", "서울")
member2 = Member("홍길동", 20, "h@h.co.kr", "서울")
print(member1)
print(member2)
print(member1==1)
print(member1==member2)

 이름 홍길동 나이 20 메일 h@h.co.kr 서울 주거중
 이름 홍길동 나이 20 메일 h@h.co.kr 서울 주거중
False
True

In [51]:
member_list = [Member("김길동", 30, "k@k.com", "서울"),
               Member("이길동", 30, "l@l.com", "인천"),
               Member("박길동", 30, "p@p.com", "수원")]
for member in member_list:
    print(member)

 이름 김길동 나이 30 메일 k@k.com 서울 주거중
 이름 이길동 나이 30 메일 l@l.com 인천 주거중
 이름 박길동 나이 30 메일 p@p.com 수원 주거중

In [55]:
with open('data/ch09_member2.json', 'w', encoding='utf-8')as jsonfile:
    json.dump(member_list, # 객체 리스트
             jsonfile, ensure_ascii=False, indent='\t',
             default=Member.as_dict) # 객체를 딕셔너리 형태로 return하는 인스턴스 함수(일반함수)

## 4.2 JSOM load (파일 읽기)
1. json파일을 딕셔너리리스트로 읽기(member1.json - utf-8)
2. json파일을 객체리스트 변수로 읽기(member2.json - cp949)

In [56]:
# 1.json파일을 딕셔너리 리스트로
with open('data/ch09_member1.json', 'r', encoding='utf-8') as jsonfile:
    load_data = json.load(jsonfile)

In [63]:
# data == (dump) ==> member1.json == (load) ==> load_data
result = [] # 두 딕셔너리의 item들이 같은지 T/F가 append
for d, load_d in zip(data, load_data):
    result.append(d==load_d)
#     print('전', d)
#     print('후', load_d)
all(result)

True

In [66]:
# json파일을 객체리스트로(member2.json)
def as_member(dic):
    '딕셔너리 데이터를 매개변수로 받아 Member 객체로 반환하는 함수'
    return Member(dic.get('name'), dic.get('age'), dic.get('email'), dic.get('address'))

In [67]:
m = as_member({'name':'김', 'age':33, 'email':'k@k.com', 'address':'서울'})
print(m)

 이름 김 나이 33 메일 k@k.com 서울 주거중

In [69]:
with open('data/ch09_member2.json', 'r', encoding='utf-8') as jsonfile:
    load_member_list = json.load(jsonfile, object_hook=as_member)

In [70]:
type(load_member_list), type(load_member_list[0])

(list, __main__.Member)

In [72]:
# memver_list == (dump) ==> memver2.json == (load) ==> load_member_list
result = []
for member, load_member in zip(member_list, load_member_list):
    result.append(member==load_member) # result 에 두 변수가 같은지 T/F
all(result) # result에 다 True인지

True

# 5절. hdf5/5h파일 쓰고 읽기
- 딥러닝 모델 저장용도(h5, keras) 
- 데이터프레임을 저장하고 읽기

In [73]:
import seaborn as sns
iris_df = sns.load_dataset("iris")
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [74]:
# 데이터프레임을 hdf(h5/hdf5)파일로 쓰기
iris_df.to_hdf('data/ch09_iris.h5', key='iris')

In [75]:
# hdf(h5/hdf5)파일을 데이터프레임으로 읽기
import pandas as pd 
load_iris_df = pd.read_hdf('data/ch09_iris.h5', key='iris')
load_iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [76]:
# iris_df ====> h5파일 ====> load_iris_df
all(iris_df==load_iris_df)

True

# 6절. 연습문제 : 실습형
- 프로그램시작시 : 
    * data/ch09_customers.txt 파일이 있으면 파일 input => customers_list(Customers형객체 list)
    * data/ch09_customers.txt 파일이 없으면 빈 파일 생성
- data/ch09_customers.txt 파일 내용은
```
홍길동, 010-9999-9999, k@hong.com, 30, 5, vvip
유길동, 010-5432-2222, y@hong.com, 20, 2, 가칠해
신림동, 010-8888-8888, s@song.com, 33, 3, 글쎄
홍길동, 010-7777-7777, h@hong.com, 33, 4, vip

```
## Customer 클래스 작성
    * customers("홍길동", "010-9999-9999", "k@hong.com", "30", "5", "vvip")
    * __init__, __str__, as_dict, to_txt_style(객체를 text style 파일로 출력하기 위해)

In [5]:
class Customer:
    def __init__(self, name, phone, email, age, grade, etc):
        self.name = name
        self.phone = phone
        self.email = email
        self.age = age
        self.grade = grade
        self.etc = etc
    def as_dict(self):
        return self.__dict__
    def __str__(self): # ***    홍길동    010-9999-9999    k@k.com    30    vvip
        return "{:5}\t{:3}\t{:15}\t{:15}\t{:3}\t{}".format(self.grade*'*',
                                                           self.name, 
                                                           self.phone,
                                                           self.email,
                                                           self.age,
                                                           self.etc)
    def to_txt_style(self): # "홍길동", "010-9999-9999", "k@hong.com", "30", "5", "vvip"
        return " {}, {}, {}, {}, {}, {}".format(self.name, 
                                                self.phone,
                                                self.email,
                                                self.age,
                                                self.grade,
                                                self.etc)

In [6]:
c1 = Customer("홍길동", "010-9999-9999", "h@h.com", 30, 4, "기타")
print(c1.as_dict())
print(c1)
print(c1.to_txt_style())

{'name': '홍길동', 'phone': '010-9999-9999', 'email': 'h@h.com', 'age': 30, 'grade': 4, 'etc': '기타'}
**** 	홍길동	010-9999-9999  	h@h.com        	 30	기타
 홍길동, 010-9999-9999, h@h.com, 30, 4, 기타

In [7]:
def to_customer(row): # "홍길동, 010-9999-9999, k@hong.com, 30, 5, vvip\n" => customer 객체
    data = row.strip().split(', ')
    name = data[0]
    phone = data[1]
    email = data[2]
    age = int(data[3])
    grade = int(data[4])
    etc = data[5]
    return Customer(name, phone, email, age, grade, etc)

In [8]:
c = to_customer("홍길동, 010-9999-9999, k@hong.com, 30, 5, vvip\n")
print(c)

*****	홍길동	010-9999-9999  	k@hong.com     	 30	vvip

## 0.처음 실행
```
    data/ch09_customer.txt 파일 내용을 customer_list에 입력받고 customer_list를 return
    
    data/ch09_customer.txt 빈 파일을 생성하고 customer_list=[] customer_list를 return
```

In [9]:
def load_customers():
    customer_list = []
    # 파일에 입력받은 customer정보를 append
    try:
        with open('data/ch09_customers.txt', 'r', encoding='utf-8') as f:
            lines = f.readlines()
            for line in lines:
                customer = to_customer(line)
                customer_list.append(customer)
    except FileNotFoundError:
        print('데이터 파일 ch09_customers.txt가 없어서 초기화 했습니다')
        with open('data/ch09_customers.txt', 'w', encoding='utf-8') as f: 
            f.write('')
    return customer_list

In [10]:
customer_list = load_customers()
for customer in customer_list:
    print(customer)

*****	홍길동	010-9999-9999  	k@hong.com     	 30	vvip
**   	유길동	010-5432-2222  	y@hong.com     	 20	가칠해
***  	신림동	010-8888-8888  	s@song.com     	 33	글쎄
**** 	홍길동	010-7777-7777  	h@hong.com     	 33	vip

## 1. 입력

In [11]:
def fn1_insert_customer_info():
    '사용자로부터 고객정보를 입력받아 Customer형 객체를 return'
    import re
    name = input('이름 : ')
    name_pattern = r'[가-힣]{2,}'
    while not re.search(name_pattern, name):
        print('이름을 제대로 입력하세요. (한글 2글자 이상)')
    phone = input('전화 : ')
    email = input('메일 : ')
    while True:
        try:
            age = int(input('나이 : '))
            if (age<=0) | (age>130):
                raise Exception("나이 범위 이상")
            break
        except:
            print('나이를 다시 입력해주세요.')
    try:
        grade = int(input('등급(1~5) : '))
        if grade < 1 :
              grade = 1
        if grade > 5 :
             grade = 5
    except:
        grade = 1
        print('유효하지 않는 등급 입력시 1등급으로 초기화')
    etc = input('기타 정보 : ')
    return Customer(name, phone, email, age, grade, etc)

In [12]:
customer_list = load_customers()
customer = fn1_insert_customer_info()
customer_list.append(customer)
for customer in customer_list:
    print(customer)

이름 : 신건우
전화 : 010-1234-5678
메일 : s@naver.com
나이 : 20
등급(1~5) : 5
기타 정보 : 없음
*****	홍길동	010-9999-9999  	k@hong.com     	 30	vvip
**   	유길동	010-5432-2222  	y@hong.com     	 20	가칠해
***  	신림동	010-8888-8888  	s@song.com     	 33	글쎄
**** 	홍길동	010-7777-7777  	h@hong.com     	 33	vip
*****	신건우	010-1234-5678  	s@naver.com    	 20	없음

## 2. 전체출력

In [164]:
def fn2_print_customer(customer_list):
    'customer_list를 출력(pdf 41p.처럼)'
    print("="*60)
    print("{:^50}".format('고객정보'))
    print("─"*31)
    print("{:>5}    {:3}      {:12}  {:15}{:3}{}".format("GRADE",
                                                      "이름",
                                                      "전화",
                                                      "메일",
                                                      "나이",
                                                      "기타"))
    print("="*60)
    for customer in customer_list:
        print(customer)

In [165]:
fn2_print_customer(customer_list)

============================================================
                       고객정보
───────────────────────────────
GRADE    이름       전화            메일             나이 기타
============================================================
*****	홍길동	010-9999-9999  	k@hong.com     	 30	vvip
**   	유길동	010-5432-2222  	y@hong.com     	 20	가칠해
***  	신림동	010-8888-8888  	s@song.com     	 33	글쎄
**** 	홍길동	010-7777-7777  	h@hong.com     	 33	vip

## 3. 종료

In [85]:
def fn3_save_customer_txt(customer_list):
    'customer_list(객체list)의 내용을 ch09_customer.txt에 백업'
    customer_text_list = []
    for customer in customer_list:
        text = customer.to_txt_style()+'\n'
        customer_text_list.append(text)
    with open('data/ch09.customers.txt', 'w', encoding='utf-8') as f:
        f.writelines(customer_text_list)
    print("백업 종료합니다. 다신 보지말아요")

In [86]:
fn3_save_customer_txt(customer_list)

백업 종료합니다. 다신 보지말아요

## main()

In [92]:
def main():
    global customer_list
    customer_list = load_customers() # 파일 내용을 customer_list로
    while True:
        print(" 1. 입력, 2 : 전체출력, 3 : 백업후 종료", sep="|", end=" ")
        fn = int(input('메뉴선택 : '))
        if fn ==1:
            customer = fn1_insert_customer_info() # 입력받은 내용으로 customer 객체 반환
            customer_list.append(customer)
        elif fn==2:
            fn2_print_customer(customer_list)
        elif fn==3:
            fn3_save_customer_txt(customer_list)
            break

In [133]:
if __name__=='__main__':
    main()

 1. 입력, 2 : 전체출력, 3 : 백업후 종료 메뉴선택 : 2
============================================================
                       고객정보
───────────────────────────────
GRADE    이름        전화          메일             나이 기타
============================================================
*****	홍길동	010-9999-9999  	k@hong.com     	 30	vvip
**   	유길동	010-5432-2222  	y@hong.com     	 20	가칠해
***  	신림동	010-8888-8888  	s@song.com     	 33	글쎄
**** 	홍길동	010-7777-7777  	h@hong.com     	 33	vip
 1. 입력, 2 : 전체출력, 3 : 백업후 종료 메뉴선택 : 3
백업 종료합니다. 다신 보지말아요